AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  comicker-api
  SAM Template for comicker-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Parameters:
  System:
    Type: String
    Description: Defines the system we are running in
    Default: prod

Resources:
  ComickerCommon:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: common
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8

  GetAllComicsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/get_all_comics
      Handler: get_all_comics.get_all_comics_handler
      Runtime: python3.8
      Environment:
        Variables:
          SYSTEM: !Ref System
          PYTHONWARNINGS: ignore
      Events:
        ComickerApi:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /comics/{pageId}
            Method: get
      Role: arn:aws:iam::171911271663:role/comicker-backend-lambda-role
      Layers:
        - arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python-AWS-SDK:4
        - !Ref ComickerCommon

  GetComicFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/get_comic
      Handler: get_comic.get_comic_handler
      Runtime: python3.8
      Environment:
        Variables:
          SYSTEM: !Ref System
          PYTHONWARNINGS: ignore
      Events:
        ComickerApi:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /comics/comic/{comicId}
            Method: get
      Role: arn:aws:iam::171911271663:role/comicker-backend-lambda-role
      Layers:
        - arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python-AWS-SDK:4
        - !Ref ComickerCommon

  CreateComicFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/create-comic/
      Handler: create_comic.create_comic_handler
      Runtime: python3.8
      Environment:
        Variables:
          SYSTEM: !Ref System
          PYTHONWARNINGS: ignore
      Events:
        ComickerApi:
          Type: HttpApi
          Properties:
            Path: /comics/create
            Method: post
      Role: arn:aws:iam::171911271663:role/comicker-backend-lambda-role
      Layers:
        - arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python-AWS-SDK:4
        - !Ref ComickerCommon


  voteOnComicFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/vote-on-comic/
      Handler: vote_on_comic.vote_on_comic_panel_handler
      Runtime: python3.8
      Environment:
        Variables:
          SYSTEM: !Ref System
          PYTHONWARNINGS: ignore
      Events:
        ComickerApi:
          Type: HttpApi
          Properties:
            Path: /comics/{comicId}/vote
            Method: put
      Role: arn:aws:iam::171911271663:role/comicker-backend-lambda-role
      Layers:
        - arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python-AWS-SDK:4
        - !Ref ComickerCommon
